import 'product.dart';

class MyProducts {
  static List<Product> electronics = [
    Product(
      id: 42,
      name: 'LG Tv 42 inch',
      category: 'Electronics',
      price: 21999,
      description: 'Experience vibrant colors and exceptional clarity with the LG 42-inch TV, perfect for home entertainment.',
      image: 'http://www.lg.com/us/images/tvs/md05802269/gallery/medium01.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Samsung Tv 40 inch',
      category: 'Electronics',
      price: 20999,
      description: 'Enjoy your favorite shows in stunning quality with the Samsung 40-inch TV, featuring smart capabilities.',
      image: 'https://www.vhv.rs/dpng/d/103-1030804_flat-screen-background-transparent-tv-hd-png-download.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Panasonic Tv',
      category: 'Electronics',
      price: 19999,
      description: 'The Panasonic TV delivers crisp images and rich sound, ideal for any living room setup.',
      image: 'https://images-na.ssl-images-amazon.com/images/I/61Ekm1BJYbL._SX355_.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Lonely TV',
      category: 'Electronics',
      price: 10,
      description: 'Well yea, this TV is lonely. But anyone can buy it for just 10 dollars! Then why don\'t they...',
      image: 'https://p1.hiclipart.com/preview/660/858/576/old-tv-s-vintage-cathode-ray-tube-television-thumbnail.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Sony Tv 50 inch',
      category: 'Electronics',
      price: 28999,
      description: 'Immerse yourself in a cinematic experience with the Sony 50-inch TV, boasting ultra HD resolution.',
      image: 'https://png.pngitem.com/pimgs/s/3-30880_download-haier-tv-png-flat-screen-tv-png.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Sharp Tv',
      category: 'Electronics',
      price: 29999,
      description: 'Get brilliant picture quality and sleek design with the Sharp TV, perfect for modern homes.',
      image: 'https://www.vhv.rs/dpng/d/1-12988_tv-with-transparent-background-hd-png-download.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Toshiba Tv',
      category: 'Electronics',
      price: 32999,
      description: 'Toshiba TV offers exceptional performance with advanced features for an enhanced viewing experience.',
      image: 'http://www.1a20.com/wp-content/uploads/2012/11/4758734_S1E2.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Vizio Tv',
      category: 'Electronics',
      price: 51999,
      description: 'The Vizio TV combines smart technology with stunning visuals, ideal for any entertainment setup.',
      image: 'https://p7.hiclipart.com/preview/410/985/299/4k-resolution-ultra-high-definition-television-samsung-smart-tv-tv-backdrop.jpg',
      quantity: 1,
    ),
  ];

  static List<Product> clothing = [
    Product(
      id: 42,
      name: 'Bean Bag',
      category: 'Furniture',
      price: 2999,
      description: 'Relax in comfort with this stylish and versatile bean bag, perfect for any room in your home.',
      image: 'https://img.freepik.com/free-psd/bean-bag-chair-isolated-transparent-background_191095-12866.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Sofa Set',
      category: 'Furniture',
      price: 20000,
      description: 'Upgrade your living space with this elegant and comfortable sofa set, perfect for family gatherings.',
      image: 'https://p7.hiclipart.com/preview/348/311/688/table-couch-furniture-living-room-chair-sofa-set.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Almirah',
      category: 'Furniture',
      price: 11500,
      description: 'Keep your belongings organized with this spacious and durable almirah, ideal for any bedroom.',
      image: 'https://img3.exportersindia.com/product_images/bc-small/dir_150/4491558/stainless-steel-almirah-1506398699-3355017.jpeg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Bed',
      category: 'Furniture',
      price: 45000,
      description: 'Sleep in luxury with this high-quality bed, offering exceptional comfort and support.',
      image: 'http://pngimg.com/uploads/bed/bed_PNG17401.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Office Chair',
      category: 'Furniture',
      price: 6999,
      description: 'Work comfortably with this ergonomic office chair, designed to provide excellent support and style.',
      image: 'http://www.freepngimg.com/thumb/chair/4-office-chair-png-image-thumb.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Dining Table',
      category: 'Furniture',
      price: 16999,
      description: 'Enhance your dining experience with this elegant dining table, perfect for family meals and gatherings.',
      image: 'https://img.freepik.com/free-psd/kitchen-table-isolated-transparent-background_191095-13975.jpg',
      quantity: 1,
    ),
  ];

  static List<Product> groceries = [
    Product(
      id: 42,
      name: 'Iron',
      category: 'Home Appliances',
      price: 1999,
      description: 'Keep your clothes wrinkle-free with this efficient and easy-to-use iron.',
      image: 'http://pngimg.com/uploads/iron/iron_PNG15563.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Mixer Juicer',
      category: 'Home Appliances',
      price: 8999,
      description: 'Blend and mix your favorite ingredients with ease using this powerful mixer juicer.',
      image: "https://images.philips.com/is/image/PhilipsConsumer/HL7715_00-IMS-en_IN?wid=494&hei=435&",
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Food Processor',
      category: 'Home Appliances',
      price: 4999,
      description: 'Prepare delicious meals effortlessly with this versatile and high-performance food processor.',
      image: 'https://p7.hiclipart.com/preview/830/24/928/mixer-blender-food-processor-home-appliance-juicer-food-processor.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Microwave',
      category: 'Home Appliances',
      price: 10000,
      description: 'Quickly heat and cook your food with this reliable and easy-to-use microwave.',
      image: 'https://image.similarpng.com/very-thumbnail/2020/08/Microwave-oven-icon-on-transparent-background-PNG.png',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Sandwich Maker',
      category: 'Home Appliances',
      price: 1800,
      description: 'Make delicious sandwiches quickly and easily with this convenient sandwich maker.',
      image: 'https://p7.hiclipart.com/preview/37/649/264/croque-monsieur-toast-barbecue-panini-gridiron-sandwich-maker-thumbnail.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Air Fryer',
      category: 'Home Appliances',
      price: 5500,
      description: 'Enjoy healthier fried foods with this innovative and efficient air fryer.',
      image: 'https://img.freepik.com/premium-psd/black-electric-air-fryer-png-transparent-background_840989-7839.jpg',
      quantity: 1,
    ),
    Product(
      id: 42,
      name: 'Playstation',
      category: 'Home Appliances',
      price: 36000,
      description: 'Experience the ultimate gaming with the latest Playstation console, offering stunning graphics and performance.',
      image: 'https://p7.hiclipart.com/preview/305/624/859/twisted-metal-black-playstation-2-playstation-4-playstation-3-others.jpg',
      quantity: 1,
    ),
  ];
}
