// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBHfG3raGlAzEMQz3mK_5m3GLA5Cc4-PE',
    appId: '1:22973581826:web:90752d72e09a17a4dab51b',
    messagingSenderId: '22973581826',
    projectId: 'shopping-core-31991',
    authDomain: 'shopping-core-31991.firebaseapp.com',
    storageBucket: 'shopping-core-31991.appspot.com',
    measurementId: 'G-SLS2DBFRFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9z2uKCBK185RFCxPPuVE3SRcam7OBwdQ',
    appId: '1:22973581826:android:3bfbff25610a2e03dab51b',
    messagingSenderId: '22973581826',
    projectId: 'shopping-core-31991',
    storageBucket: 'shopping-core-31991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyLSkpgYxgXd4oGxxNbBfOCynDadNxDtk',
    appId: '1:22973581826:ios:2c0d60beda43c6d4dab51b',
    messagingSenderId: '22973581826',
    projectId: 'shopping-core-31991',
    storageBucket: 'shopping-core-31991.appspot.com',
    iosBundleId: 'com.example.shoppingCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyLSkpgYxgXd4oGxxNbBfOCynDadNxDtk',
    appId: '1:22973581826:ios:2c0d60beda43c6d4dab51b',
    messagingSenderId: '22973581826',
    projectId: 'shopping-core-31991',
    storageBucket: 'shopping-core-31991.appspot.com',
    iosBundleId: 'com.example.shoppingCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBHfG3raGlAzEMQz3mK_5m3GLA5Cc4-PE',
    appId: '1:22973581826:web:db63c8d335bd4b8cdab51b',
    messagingSenderId: '22973581826',
    projectId: 'shopping-core-31991',
    authDomain: 'shopping-core-31991.firebaseapp.com',
    storageBucket: 'shopping-core-31991.appspot.com',
    measurementId: 'G-RTCP8JMY39',
  );
}
